### ISSUE TITLE
Wrong/missing blacklist entries

### ISSUE THREAD

**Issue by mbechler** [Contrast-Security-OSS/contrast-rO0#1]
And, copied again ;)

Not that I would count on the blacklist, but seemingly everyone is copying around these blacklists that are not really getting the root cause of the spring vector. The piece of code that gives the arbitrary method invocation is

org.springframework.core.SerializableTypeWrapper$MethodInvokeTypeProvider

, so that should be blacklisted.

**Comment by nahsra** [comment]
Thanks! I think everyone is trying to get the least impactful patch together. That is indeed a crazy gadget.  I added it to the blacklist.
